services:
  main:
    build:
      context: .
      args:
        - ARCHITECTURE=x86
        - OPENSSL_VERSION=3.2.0
        - TCL_VERSION=16.x
      tags:
        - linichotmailca/openssl-i586:3.2.0
        - linichotmailca/openssl-i586:latest
      dockerfile: Dockerfile

